version: "3"
services:
  app:
    build:
      context: ./my-app
      dockerfile: Dockerfile-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - server

  server:
    build:
      context: ./my-app/backend
      dockerfile: Dockerfile-server
    ports:
      - "5000:5000"
